### ISSUE TITLE
Using this now gets you auto flagged for bot watchlist

### ISSUE THREAD

**Issue by nicole0902** [Ryuuhou/AHKanColle#14]
I suggest to not use any simple script macros as KDKW tracks mouse click locations from the client

**Comment by Ryuuhou** [comment]
Do you have a reputable source for this information? I have not been following the game recently.

**Comment by nicole0902** [comment]
https://github.com/mrmin123/kancolle-auto/issues/94

**Comment by mrmin123** [comment]
I just saw this being referenced, but I wanted to mention that there was another thread on the repo a while back (https://github.com/mrmin123/kancolle-auto/issues/52; doesn't exist anymore because the person who opened the issue deleted their github account) had some good discussion regarding tracking of mouse click locations. The takeaways I remember:
- Somebody posted a link to a lengthy blog post at the KancolleBot website (http://kancollebot.pixnet.net/blog) that purportedly went into dissecting the mouseclick location tracking mechanism Kadokawa added to the game. Unfortunately the site was all in Chinese, and I don't know Chinese.
- Another person had dissected the game code themselves and found the relevant mouseclick location tracking mechanism in the Flash files.
- A third person reporting that they were banned after using the tool for a few days (kancolle-auto at the time was a naive clicker at the time, just clicking the same locations repeatedly)

The above is what made me incorporate random mouseclick locations and random screen navigation into kancolle-auto to better avoid bot detection, but take from what it what you will. Hope this helps!

**Comment by Ryuuhou** [comment]
Added a random offset between -2 to 2 pixels to every click. Closing issue.
