### ISSUE TITLE
AHKCSortie not clicking on anything

### ISSUE THREAD

**Issue by FadedMazix** [Ryuuhou/AHKanColle#16]
The AHKanColle script is running fine, and will click in the background and send my expeditions out. However, the AHKCSortie Script I can't get to click for the life of me. It recognizes when the window changes, but it won't click at all, even though the status box is going through the entire script, from resupply, to sending out the sortie, to waiting for results and the home screen to come back up.

I have tried setting background to 0 to no avail, as well as defining the Window and Class specifically using Window Spy. I even switched over to the 32 bit version of AutoHotkey, to see if that might have been the problem

I am running the latest version of KCV Yuubari fork, and I am running this on windows 10.

I didn't want to ask for technical support on this, but I didn't see a similar issue to it in your issues section. So, either this is specific to me, or this is a problem that just cropped up recently.

**Comment by Ryuuhou** [comment]
I verified that it was not clicking on my end either. Turns out when I updated the main click functionality to provide for randomized clicking back in May, I did not verify that it worked with AHKCSortie.  (It was a silly mistake) It is now fixed in the latest commit https://github.com/Ryuuhou/AHKanColle/commit/b5687b3ec94523ba35ed04bfeb3930df7fcda223 and can be found in the release section.
